# Project: RougeB
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o graph.o
LINKOBJ  = main.o graph.o
LIBS     = -L"E:/Coding/devcpp_setup/MinGW64/lib" -L"E:/Coding/devcpp_setup/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -l winmm
INCS     = -I"E:/Coding/devcpp_setup/MinGW64/include" -I"E:/Coding/devcpp_setup/MinGW64/x86_64-w64-mingw32/include" -I"E:/Coding/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"E:/Coding/devcpp_setup/MinGW64/include" -I"E:/Coding/devcpp_setup/MinGW64/x86_64-w64-mingw32/include" -I"E:/Coding/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"E:/Coding/devcpp_setup/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = RougeB.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)

graph.o: graph.c
	$(CC) -c graph.c -o graph.o $(CFLAGS)
